version: '2.1'

services:

  bgminer:
    build: ./
    image: bg-miner/bg-miner
    restart: unless-stopped
    cpu_shares: 10
    cap_add:
      - SYS_NICE
    dns:
      - "8.8.8.8"
      - "8.8.4.4"
